apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-ebs
provisioner: kubernetes.io/aws-ebs  # or other provisioner like kubernetes.io/gce-pd, etc.
parameters:
  type: gp2  # Parameters specific to the provisioner, e.g., AWS EBS volume type
reclaimPolicy: Retain
volumeBindingMode: Immediate